name: Build foo2zjs

on:
  push:
    paths:
      - '*.c'
      - 'foomatic-db'
  pull_request:
    paths:
      - '*.c'
      - 'foomatic-db'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Git checkout
        uses: actions/checkout@v7

      - name: Declare short commit variable
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create cache directory
        run: mkdir ~/cache

      - id: cache
        name: Initialize cache
        uses: actions/cache@v6
        with:
          path: ~/cache
          key: cache-${{ runner.os }}

      - name: APT install
        run: |
          sudo sed -i 's~Types: ~Types: deb-src ~' /etc/apt/sources.list.d/ubuntu.sources
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -y build-essential libcups2-dev foomatic-db-engine dc cups groff nano less ninja-build
          sudo DEBIAN_FRONTEND=noninteractive apt build-dep -y cups

      - if: steps.cache.outputs.cache-hit != 'true'
        name: Build polyfill-glibc
        run: |
          git clone https://github.com/corsix/polyfill-glibc.git && cd polyfill-glibc && ninja
          cp polyfill-glibc ~/cache/

      - if: steps.cache.outputs.cache-hit != 'true'
        name: Build libjbig
        run: |
          mkdir jbig && cd jbig && apt source jbigkit
          cd jbigkit-* && make -j4
          cp libjbig/libjbig.a ~/cache/

      - name: Build foo2zjs
        run: |
          JB=$(realpath ~/cache/libjbig.a)
          # use static libjbig
          sed -i "s~^LIBJBG = .*~LIBJBG = ${JB}~" Makefile
          grep 'LIBJBG' Makefile
          make -j4
          mkdir -p output/bin
          cp $(ls -1 | grep -E '^foo2[^-.]*$') output/bin/
          cp $(ls -1 | grep -E '^foo2[^-.]*-wrapper$') output/bin/
          [ -f ~/cache/11.patch ] || wget -O ~/cache/11.patch https://github.com/OpenPrinting/foomatic-db-engine/pull/11.patch
          (cd /usr/share/perl5/Foomatic/ && sudo patch -p3 -i ~/cache/11.patch)
          (cd foomatic-db && ln -s . db  && ln -s . source)
          FOOMATICDB=foomatic-db foomatic-compiledb -d output/ppd

      - name: Patch for older glibc
        run: |
          for i in output/bin/*; do ~/cache/polyfill-glibc --target-glibc=2.17 $i || true; done

      - name: Save build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: foo2zjs_x86_64_${{ steps.vars.outputs.sha_short }}
          path: output/
